export default function getPhotos() {
    return [
        { id: 1, src: '1.jpg',  author: 'Kate Arroyo', name: 'Road in the forest', categories: ['nature'], tags: ['wood', 'sun', 'trees'] },
        { id: 2, src: '2.jpg',  author: 'Savannah Vargas', name: 'Rural life', categories: ['animals', 'nature'],  tags: ['sun', 'goats'] },
        { id: 3, src: '3.jpg',  author: 'Rehan Hayden', name: 'Art Nouveau house', categories: ['architecture'],  tags: ['building'] },
        { id: 4, src: '4.jpg',  author: 'Enya Skinner', name: 'Dietary salad', categories: ['food'],  tags: ['salad'] },
        { id: 5, src: '5.jpg',  author: 'Savannah Vargas', name: 'Running dogs', categories: ['animals'],  tags: ['dogs'] },
        { id: 6, src: '6.jpg',  author: 'Kiran Chang', name: 'Сhristmas cake', categories: ['food'],  tags: ['cake'] },
        { id: 7, src: '7.jpg',  author: 'Romeo Green', name: 'Sunset on the sea', categories: ['nature'],  tags: ['sun', 'sea', 'sky'] },
        { id: 8, src: '8.jpg',  author: 'Enya Skinner', name: 'Mountain landscape', categories: ['nature'],  tags: ['wood', 'mountains', 'sky'] },
        { id: 9, src: '9.jpg',  author: 'Marina Whitehead', name: 'Dog on the grass', categories: ['animals'],  tags: ['dog', 'grass'] },
        { id: 10, src: '10.jpg', author: 'Romeo Green', name: 'Modern architecture',  categories: ['architecture'],  tags: ['building'] },
        { id: 11, src: '11.jpg', author: 'Savannah Vargas', name: 'Vegetable soup',  categories: ['food'],  tags: ['soup'] },
        { id: 12, src: '12.jpg', author: 'Rehan Hayden', name: 'Romantic landscape',  categories: ['art'],  tags: ['art', 'tree', 'grass'] },
        { id: 13, src: '13.jpg', author: 'Kate Arroyo', name: 'Sun in the forest',  categories: ['nature'],  tags: ['wood', 'sun', 'trees'] },
        { id: 14, src: '14.jpg', author: 'Luna Elliott', name: 'Life in Venice',  categories: ['art'],  tags: ['art', 'water'] },
        { id: 15, src: '15.jpg', author: 'Enya Skinner', name: 'Tiger in the wild',  categories: ['animals', 'nature'],  tags: ['tiger'] },
        { id: 16, src: '16.jpg', author: 'Marina Whitehead', name: 'The cat sleeps sweetly',  categories: ['animals'],  tags: ['cat'] },
        { id: 17, src: '17.jpg', author: 'Savannah Vargas', name: 'Abstract face',  categories: ['art'],  tags: ['art', 'face'] },
        { id: 18, src: '18.jpg', author: 'David Odom', name: 'King of the birds',  categories: ['animals', 'nature'],  tags: ['eagle'] },
        { id: 19, src: '19.jpg', author: 'Luna Elliott', name: 'Mountain Lake',  categories: ['nature'],  tags: ['mountains', 'sky', 'mountains'] },
        { id: 20, src: '20.jpg', author: 'Kate Arroyo', name: 'Gray cat',  categories: ['animals'],  tags: ['cat'] },
        { id: 21, src: '21.jpg', author: 'Kiran Chang', name: 'Dog on a walk',  categories: ['animals'],  tags: ['dog', 'grass'] },
        { id: 22, src: '22.jpg', author: 'Savannah Vargas', name: 'Hand drawn city',  categories: ['art'],  tags: ['art', 'building', 'city'] },
        { id: 23, src: '23.jpg', author: 'Kate Arroyo', name: 'Modern city',  categories: ['architecture'],  tags: ['building', 'city'] },
        { id: 24, src: '24.jpg', author: 'David Odom', name: 'Tree blossom',  categories: ['nature'],  tags: ['trees', 'flowers'] },
        { id: 25, src: '25.jpg', author: 'Rehan Hayden', name: 'Sakura in spring',  categories: ['nature'],  tags: ['trees', 'flowers'] },
        { id: 26, src: '26.jpg', author: 'Kate Arroyo', name: 'Flower field',  categories: ['nature'],  tags: ['grass', 'flowers'] },
        { id: 27, src: '27.jpg', author: 'Eugene Pace', name: 'King burger',  categories: ['food'],  tags: ['burger', 'fastfood'] },
        { id: 28, src: '28.jpg', author: 'Enya Skinner', name: 'Domestic cat',  categories: ['animals'],  tags: ['cat'] },
        { id: 29, src: '29.jpg', author: 'Savannah Vargas', name: 'Modern residential area',  categories: ['architecture'],  tags: ['building', 'city'] },
        { id: 30, src: '30.jpg', author: 'David Odom', name: 'Dog on the lawn',  categories: ['animals'],  tags: ['dog', 'grass', 'sun'] },
        { id: 31, src: '31.jpg', author: 'Kate Arroyo', name: 'Old city',  categories: ['architecture'],  tags: ['building', 'city'] },
        { id: 32, src: '32.jpg', author: 'Rehan Hayden', name: 'Italian pasta',  categories: ['food'],  tags: ['pasta'] },
        { id: 33, src: '33.jpg', author: 'Kate Arroyo', name: 'Pumpkin cream soup',  categories: ['food'],  tags: ['soup'] },
        { id: 34, src: '34.jpg', author: 'Romeo Green', name: 'Ciabatta',  categories: ['food'],  tags: ['sandwich', 'fastfood'] },
        { id: 35, src: '35.jpg', author: 'Savannah Vargas', name: 'Fruit dessert',  categories: ['food'],  tags: ['cake', 'fruits'] },
        { id: 36, src: '36.jpg', author: 'Kate Arroyo', name: 'Pizza Assorted',  categories: ['food'],  tags: ['fastfood', 'fastfood'] },
        { id: 37, src: '37.jpg', author: 'Eugene Pace', name: 'Chocolate pie',  categories: ['food'],  tags: ['cake', 'chocolate', 'fruits'] },
        { id: 38, src: '38.jpg', author: 'Kate Arroyo', name: 'Herd of zebras',  categories: ['animals', 'nature'],  tags: ['zebras'] },
        { id: 39, src: '39.jpg', author: 'David Odom', name: 'Sunflower pod',  categories: ['nature'],  tags: ['flowers', 'sun', 'sunflower', 'field'] },
        { id: 40, src: '40.jpg', author: 'Rehan Hayden', name: 'Old quarter',  categories: ['architecture'],  tags: ['building', 'city', 'street', 'quarter'] },
        { id: 41, src: '41.jpg', author: 'Enya Skinner', name: 'Meadow',  categories: ['nature'],  tags: ['river', 'mountains', 'sky', 'meadow'] },
        { id: 42, src: '42.jpg', author: 'Savannah Vargas', name: 'People movement',  categories: ['art'],  tags: ['art', 'people', 'movement'] }
    ];
}